# Generated by Django 5.1.4 on 2025-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_moviereview_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
